# SPDX-FileCopyrightText: 2026 A. Pettersson, DESY
# SPDX-License-Identifier: CC0-1.0

[_default]
_autonomy.role = "DYNAMIC"

# --- Stage ---------------------------------------------------------------------
[Standa.Stage]
model = "8MT30_50"
calibrate_on_launch = false

[Standa.Stage.axis_serials]
x = 31015
y = 31016
z = 30954

[Standa.Stage.position]
x = 40.0
y = 40.0
z = 0.0

# --- Bias voltage ----------------------------------------------------------------
[Keithley.HV]
device = "2410"
port = "/dev/ttyUSB0"
terminal = "rear"
voltage = -1.0
voltage_step = 5.0
settle_time = 1.0
ovp = 200.0
compliance = 1e-5

# --- Oscilloscope ----------------------------------------------------------------
# LeCrunch on TCP port 1861 requires "TCPIP (VICP)" under Utilities -> Remote
[LeCroySatellite.Scope]
#ip_address = "169.254.40.151"
ip_address = "10.12.164.48"
port = 1861
timeout = 5.0
nsequence = 1

# --- Data writer -----------------------------------------------------------------
[H5DataWriter.Writer]
output_directory = "/home/andreas/Work/DESY/tct/data"
flush_interval = 10.0

[H5DataWriter.Writer._data]
receive_from = ["LeCroySatellite.Scope"]
