# SPDX-FileCopyrightText: 2026 A. Pettersson, DESY
# SPDX-License-Identifier: CC0-1.0

[_default]
_autonomy.role = "DYNAMIC"

# --- Stage ---------------------------------------------------------------------
[Standa.Stage]
model = "8MT30_50"
calibrate_on_launch = false

[Standa.Stage.axis_serials]
x = 31015
y = 31016
z = 30954

[Standa.Stage.position]
x = 0.0
y = 0.0
z = 0.0

# --- Bias voltage ----------------------------------------------------------------
[Keithley.HV]
device = "2410"
port = "/dev/ttyUSB1"
terminal = "rear"
voltage = 0.0
voltage_step = 1.0
settle_time = 2.0
ovp = 200.0
compliance = 305e-3

# --- Data writer -----------------------------------------------------------------
[H5DataWriter.Writer]
output_directory = "/home/alibava/tct/data"
flush_interval = 10.0

[H5DataWriter.Writer._data]
receive_from = ["Alibava.DAQ"]

# --- DAQ -------------------------------------------------------------------------
[Alibava.DAQ]
device = "/dev/serial/by-id/usb-FTDI_FT245R_USB_FIFO_A70476NF-if00-port0"
run_type = "Pedestal"
sample_size = 10
daq_delay = 10
daq_enable_busy = true
daq_pulse_shape = false

stop_timeout = 10
reset_board = true

_autonomy.role = "NONE"
_data.bor_timeout = 2 #60
_data.data_timeout = 60
_data.eor_timeout = 60

[Alibava.DAQ.trigger]
type = "TriggerPulse"
setup = "TriggerOR"
#dac_pulse_pos = 1.5
dac_pulse_neg = -1500

[Alibava.DAQ.beetle_0]
latency = 134

[Alibava.DAQ.beetle_1]
latency = 134
